version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo Running tests...
      - pytest --maxfail=1 --disable-warnings -q

  build:
    commands:
      - echo Build phase complete.

artifacts:
  files:
    - '**/*'
